# Usamos la imagen oficial de Nginx
FROM nginx:alpine

# Copiamos los archivos estáticos de la aplicación web al contenedor
COPY . /usr/share/nginx/html


# Exponemos el puerto por defecto de Nginx
EXPOSE 80
