# Usamos la imagen oficial de MariaDB
FROM mariadb:latest

# Configuración de la base de datos (estos valores se pueden gestionar también desde docker-compose.yml)
ENV MYSQL_DATABASE=floreria
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=contraseña
ENV MYSQL_ROOT_PASSWORD=contraseña_root

# Exponemos el puerto por defecto de MariaDB
EXPOSE 3306
