INSERT INTO desserts (name)
VALUES 

('Pudin de Arroz'),
('Pudin de Chocolate'),
('Helado de Frambuesa'),
('Mousse de Limón'),
('Tarta de Frambuesa'),
('Galletas de Frambuesa'),
('Helado de Limón'),
('Tarta de Lima'),
('Tarta de Piña'),
('Bizcocho de Yogur'),
('Helado de Mango'),
('Galletas de Maicena'),
('Mousse de Piña'),
('Tarta de Coco'),
('Galletas de Plátano'),
('Galletas de Avena y Chocolate'),
('Mousse de Maracuyá'),
('Helado de Maracuyá'),
('Tarta de Maracuyá'),
('Pudin de Pan'),
('Tarta de Almendra'),
('Helado de Nuez'),
('Pastel de Nuez'),
('Tarta de Nuez'),
('Helado de Almendra'),
('Galletas de Nuez Moscada'),
('Tarta de Queso y Frutas'),
('Helado de Mora'),
('Tarta de Mora'),
('Pastel de Mora'),
('Tarta de Kiwi'),
('Pastel de Kiwi'),
('Helado de Kiwi'),
('Pastel de Manzana'),
('Tarta de Pera'),
('Helado de Pera'),
('Galletas de Pera'),
('Tarta de Higos'),
('Pastel de Higos'),
('Helado de Higos'),
('Tarta de Uva'),
('Helado de Uva'),
('Pastel de Uva'),
('Tarta de Sandía'),
('Helado de Sandía'),
('Pastel de Sandía'),
('Tarta de Melón'),
('Helado de Melón'),
('Pastel de Melón'),
('Tarta de Cantalupo'),
('Helado de Cantalupo'),
('Pastel de Cantalupo'),
('Tarta de Albaricoque'),
('Helado de Albaricoque'),
('Pastel de Albaricoque'),
('Tarta de Grosella'),
('Helado de Grosella'),
('Pastel de Grosella'),
('Tarta de Granada'),
('Helado de Granada'),
('Pastel de Granada'),
('Tarta de Guayaba'),
('Helado de Guayaba'),
('Pastel de Guayaba'),
('Tarta de Litchi'),
('Helado de Litchi'),
('Pastel de Litchi'),
('Tarta de Papaya'),
('Helado de Papaya'),
('Pastel de Papaya'),
('Tarta de Pitaya'),
('Helado de Pitaya'),
('Pastel de Pitaya'),
('Tarta de Plátano'),
('Helado de Plátano'),
('Pastel de Plátano'),
('Tarta de Chirimoya'),
('Helado de Chirimoya'),
('Pastel de Chirimoya'),
('Tarta de Caqui'),
('Helado de Caqui'),
('Pastel de Caqui'),
('Tarta de Mangostán'),
('Helado de Mangostán'),
('Pastel de Mangostán'),
('Tarta de Durian'),
('Helado de Durian'),
('Pastel de Durian'),
('Tarta de Rambután'),
('Helado de Rambután'),
('Pastel de Rambután'),
('Tarta de Carambola'),
('Helado de Carambola'),
('Pastel de Carambola'),
('Tarta de Naranja Sanguina'),
('Helado de Naranja Sanguina'),
('Pastel de Naranja Sanguina'),
('Tarta de Pomelo'),
('Helado de Pomelo'),
('Pastel de Pomelo'),
('Tarta de Mandarina'),
('Helado de Mandarina'),
('Pastel de Mandarina'),
('Tarta de Pomelo Rosa'),
('Helado de Pomelo Rosa'),
('Pastel de Pomelo Rosa'),
('Tarta de Kumquat'),
('Helado de Kumquat'),
('Pastel de Kumquat'),
('Tarta de Longan'),
('Helado de Longan'),
('Pastel de Longan'),
('Tarta de Physalis'),
('Helado de Physalis'),
('Pastel de Physalis'),
('Tarta de Tamarillo'),
('Helado de Tamarillo'),
('Pastel de Tamarillo'),
('Tarta de Feijoa'),
('Helado de Feijoa'),
('Pastel de Feijoa'),
('Tarta de Jabuticaba'),
('Helado de Jabuticaba'),
('Pastel de Jabuticaba'),
('Tarta de Capulín'),
('Helado de Capulín'),
('Pastel de Capulín'),
('Tarta de Caimito'),
('Helado de Caimito'),
('Pastel de Caimito'),
('Tarta de Mamey'),
('Helado de Mamey'),
('Pastel de Mamey'),
('Tarta de Guabirá'),
('Helado de Guabirá'),
('Pastel de Guabirá'),
('Tarta de Guapurú'),
('Helado de Guapurú'),
('Pastel de Guapurú'),
('Tarta de Aguaymanto'),
('Helado de Aguaymanto'),
('Pastel de Aguaymanto'),
('Tarta de Tucumán'),
('Helado de Tucumán'),
('Pastel de Tucumán'),
('Tarta de Ciruela Kakadu'),
('Helado de Ciruela Kakadu'),
('Pastel de Ciruela Kakadu'),
('Tarta de Nance'),
('Helado de Nance'),
('Pastel de Nance'),
('Tarta de Chayote'),
('Helado de Chayote'),
('Pastel de Chayote'),
('Tarta de Fruta del Pan'),
('Helado de Fruta del Pan'),
('Pastel de Fruta del Pan'),
('Tarta de Jackfruit'),
('Helado de Jackfruit'),
('Pastel de Jackfruit'),
('Tarta de Abiu'),
('Helado de Abiu'),
('Pastel de Abiu'),
('Tarta de Santol'),
('Helado de Santol'),
('Pastel de Santol'),
('Tarta de Noni'),
('Helado de Noni'),
('Pastel de Noni'),
('Tarta de Fruta de Monje'),
('Helado de Fruta de Monje'),
('Pastel de Fruta de Monje'),
('Tarta de Guineo'),
('Helado de Guineo'),
('Pastel de Guineo'),
('Tarta de Gac'),
('Helado de Gac'),
('Pastel de Gac'),
('Tarta de Fresa China'),
('Helado de Fresa China'),
('Pastel de Fresa China'),
('Tarta de Manzana Estrella'),
('Helado de Manzana Estrella'),
('Pastel de Manzana Estrella'),
('Tarta de Durazno Plano'),
('Helado de Durazno Plano'),
('Pastel de Durazno Plano'),
('Tarta de Arándano Ojo de Pájaro'),
('Helado de Arándano Ojo de Pájaro'),
('Pastel de Arándano Ojo de Pájaro'),
('Tarta de Yaca'),
('Helado de Yaca'),
('Pastel de Yaca'),
('Tarta de Anón'),
('Helado de Anón'),
('Pastel de Anón'),
('Tarta de Icaco'),
('Helado de Icaco'),
('Pastel de Icaco'),
('Tarta de Sapote Negro'),
('Helado de Sapote Negro'),
('Pastel de Sapote Negro'),
('Tarta de Chirimoya Roja'),
('Helado de Chirimoya Roja'),
('Pastel de Chirimoya Roja'),
('Tarta de Manzano de Sodoma'),
('Helado de Manzano de Sodoma'),
('Pastel de Manzano de Sodoma'),
('Tarta de Fruta Milagrosa'),
('Helado de Fruta Milagrosa'),
('Pastel de Fruta Milagrosa'),
('Tarta de Baya de Goji'),
('Helado de Baya de Goji'),
('Pastel de Baya de Goji'),
('Tarta de Fruta de Dragón'),
('Helado de Fruta de Dragón'),
('Pastel de Fruta de Dragón'),
('Tarta de Lulo'),
('Helado de Lulo'),
('Pastel de Lulo'),
('Tarta de Morera'),
('Helado de Morera'),
('Pastel de Morera'),
('Tarta de Fruta del Higo'),
('Helado de Fruta del Higo'),
('Pastel de Fruta del Higo'),
('Tarta de Níspero'),
('Helado de Níspero'),
('Pastel de Níspero'),
('Tarta de Fruta de Monstera'),
('Helado de Fruta de Monstera'),
('Pastel de Fruta de Monstera'),
('Tarta de Uchuva'),
('Helado de Uchuva'),
('Pastel de Uchuva'),
('Tarta de Fruta del Pájaro'),
('Helado de Fruta del Pájaro'),
('Pastel de Fruta del Pájaro'),
('Tarta de Manzana de Agua'),
('Helado de Manzana de Agua'),
('Pastel de Manzana de Agua'),
('Tarta de Limón Tahití'),
('Helado de Limón Tahití'),
('Pastel de Limón Tahití'),
('Tarta de Falsa Guayaba'),
('Helado de Falsa Guayaba'),
('Pastel de Falsa Guayaba'),
('Tarta de Falsa Granada'),
('Helado de Falsa Granada'),
('Pastel de Falsa Granada'),
('Tarta de Falsa Mora'),
('Helado de Falsa Mora'),
('Pastel de Falsa Mora'),
('Tarta de Falsa Naranja'),
('Helado de Falsa Naranja'),
('Pastel de Falsa Naranja'),
('Tarta de Falsa Uva'),
('Helado de Falsa Uva'),
('Pastel de Falsa Uva'),
('Tarta de Guayaba Fresa'),
('Helado de Guayaba Fresa'),
('Pastel de Guayaba Fresa'),
('Tarta de Guayaba Manzana'),
('Helado de Guayaba Manzana'),
('Pastel de Guayaba Manzana'),
('Tarta de Guayaba Naranja'),
('Helado de Guayaba Naranja'),
('Pastel de Guayaba Naranja'),
('Tarta de Uva de Mar'),
('Helado de Uva de Mar'),
('Pastel de Uva de Mar'),
('Tarta de Falsa Papaya'),
('Helado de Falsa Papaya'),
('Pastel de Falsa Papaya'),
('Tarta de Falsa Pera'),
('Helado de Falsa Pera'),
('Pastel de Falsa Pera'),
('Tarta de Manzana Rosa'),
('Helado de Manzana Rosa'),
('Pastel de Manzana Rosa'),
('Tarta de Uva Japonesa'),
('Helado de Uva Japonesa'),
('Pastel de Uva Japonesa'),
('Tarta de Pomelo Japonés'),
('Helado de Pomelo Japonés'),
('Pastel de Pomelo Japonés'),
('Tarta de Manzana Siberiana'),
('Helado de Manzana Siberiana'),
('Pastel de Manzana Siberiana'),
('Tarta de Pera Siberiana'),
('Helado de Pera Siberiana'),
('Pastel de Pera Siberiana'),
('Tarta de Naranja Siberiana'),
('Helado de Naranja Siberiana'),
('Pastel de Naranja Siberiana'),
('Tarta de Lima Siberiana'),
('Helado de Lima Siberiana'),
('Pastel de Lima Siberiana'),
('Tarta de Manzana Egipcia'),
('Helado de Manzana Egipcia'),
('Pastel de Manzana Egipcia'),
('Tarta de Pera Egipcia'),
('Helado de Pera Egipcia'),
('Pastel de Pera Egipcia'),
('Tarta de Naranja Egipcia'),
('Helado de Naranja Egipcia'),
('Pastel de Naranja Egipcia'),
('Tarta de Lima Egipcia'),
('Helado de Lima Egipcia'),
('Pastel de Lima Egipcia'),
('Tarta de Manzana Africana'),
('Helado de Manzana Africana'),
('Pastel de Manzana Africana'),
('Tarta de Pera Africana'),
('Helado de Pera Africana'),
('Pastel de Pera Africana'),
('Tarta de Naranja Africana'),
('Helado de Naranja Africana'),
('Pastel de Naranja Africana'),
('Tarta de Lima Africana'),
('Helado de Lima Africana'),
('Pastel de Lima Africana'),
('Tarta de Manzana Australiana'),
('Helado de Manzana Australiana'),
('Pastel de Manzana Australiana'),
('Tarta de Pera Australiana'),
('Helado de Pera Australiana'),
('Pastel de Pera Australiana'),
('Tarta de Naranja Australiana'),
('Helado de Naranja Australiana'),
('Pastel de Naranja Australiana'),
('Tarta de Lima Australiana'),
('Helado de Lima Australiana'),
('Pastel de Lima Australiana'),
('Tarta de Manzana India'),
('Helado de Manzana India'),
('Pastel de Manzana India'),
('Tarta de Pera India'),
('Helado de Pera India'),
('Pastel de Pera India'),
('Tarta de Naranja India'),
('Helado de Naranja India'),
('Pastel de Naranja India'),
('Tarta de Lima India'),
('Helado de Lima India'),
('Pastel de Lima India'),
('Tarta de Manzana China'),
('Helado de Manzana China'),
('Pastel de Manzana China'),
('Tarta de Pera China'),
('Helado de Pera China'),
('Pastel de Pera China'),
('Tarta de Naranja China'),
('Helado de Naranja China'),
('Pastel de Naranja China'),
('Tarta de Lima China'),
('Helado de Lima China'),
('Pastel de Lima China'),
('Tarta de Manzana Brasileña'),
('Helado de Manzana Brasileña'),
('Pastel de Manzana Brasileña'),
('Tarta de Pera Brasileña'),
('Helado de Pera Brasileña'),
('Pastel de Pera Brasileña'),
('Tarta de Naranja Brasileña'),
('Helado de Naranja Brasileña'),
('Pastel de Naranja Brasileña'),
('Tarta de Lima Brasileña'),
('Helado de Lima Brasileña'),
('Pastel de Lima Brasileña');
('Tarta de Limón'), 
('Cheesecake'), 
('Brownie de Chocolate'), 
('Tiramisu'), 
('Pudin de Caramelo'),
('Pastel de Zanahoria'), 
('Mousse de Chocolate'),
('Cupcake de Vainilla'), 
('Gelato de Fresa'), 
('Pie de Manzana'), 
('Pastel de Almendra'), 
('Flan de Queso'),
('Tarta de Frutos Rojos'),
('Sorbete de Mango'),
('Pastel de Queso y Frutos Rojos'),
('Helado de Chocolate con Nueces'),
('Pie de Pera'),
('Tarta de Queso con Fresas'),
('Pastel de Chocolate Blanco'),
('Panna Cotta'),
('Brownie de Nuez'),
('Helado de Menta'),
('Pastel de Coco'),
('Cheesecake de Frutos Rojos'),
('Mousse de Limón'),
('Tarta de Manzana y Canela'),
('Pastel de Vainilla y Fresas'),
('Helado de Avellana'),
('Tarta de Chocolate'),
('Pudin de Chocolate'),
('Pastel de Chocolate con Cereza'),
('Helado de Café'),
('Pie de Limón'),
('Cheesecake de Mango'),
('Tarta de Mora'),
('Pastel de Café'),
('Pastel de Limon y Merengue'),
('Helado de Frambuesa'),
('Cheesecake de Chocolate Blanco'),
('Pastel de Frutas'),
('Mousse de Frambuesa'),
('Pie de Chocolate'),
('Tarta de Pera y Almendra'),
('Helado de Plátano'),
('Pastel de Almendra y Chocolate'),
('Flan de Chocolate'),
('Tarta de Chocolate y Naranja'),
('Cheesecake de Mora'),
('Pastel de Tarta de Queso'),
('Pastel de Zanahoria y Nueces'),
('Helado de Vainilla y Caramelo'),
('Tarta de Limón y Merengue'),
('Pastel de Chocolate y Café'),
('Cheesecake de Fresa y Limón'),
('Helado de Pistacho'),
('Pie de Manzana con Canela'),
('Tarta de Arándano'),
('Pastel de Naranja'),
('Helado de Dulce de Leche'),
('Tarta de Almendra'),
('Pastel de Plátano'),
('Cheesecake de Frutos del Bosque'),
('Tarta de Frambuesa'),
('Mousse de Chocolate Blanco'),
('Pie de Limón y Merengue'),
('Helado de Coco'),
('Pastel de Chocolate y Naranja'),
('Pastel de Queso y Limón'),
('Cheesecake de Limón y Fresa'),
('Tarta de Limón y Frambuesa'),
('Helado de Chocolate con Menta'),
('Pastel de Frutas del Bosque'),
('Tarta de Fresas y Chocolate'),
('Mousse de Mango'),
('Tarta de Nuez'),
('Pastel de Frutas Secas'),
('Pie de Frambuesa'),
('Pastel de Chocolate y Almendra'),
('Cheesecake de Chocolate y Fresa'),
('Helado de Mango y Maracuyá'),
('Pie de Nuez'),
('Tarta de Queso con Arándanos'),
('Pastel de Mora'),
('Helado de Cereza'),
('Tarta de Limón con Frutos Rojos'),
('Pastel de Melocotón'),
('Cheesecake de Coco'),
('Mousse de Café'),
('Pie de Frutos del Bosque'),
('Tarta de Fresas y Crema'),
('Pastel de Chocolate con Avellanas'),
('Helado de Fresa y Menta'),
('Tarta de Chocolate y Frutos Rojos'),
('Pie de Limón con Merengue'),
('Tarta de Pera y Chocolate'),
('Pastel de Limón con Almendra'),
('Cheesecake de Chocolate y Avellanas'),
('Helado de Vainilla y Fresas'),
('Tarta de Frutos Rojos y Chocolate'),
('Pastel de Melocotón y Almendra'),
('Helado de Arándano'),
('Tarta de Chocolate con Frutos Secos'),
('Pastel de Chocolate y Plátano'),
('Cheesecake de Limón'),
('Pie de Naranja'),
('Tarta de Frutos Rojos y Nuez'),
('Pastel de Café y Nuez'),
('Tarta de Frambuesa y Chocolate'),
('Pastel de Chocolate y Fresas'),
('Helado de Fresas con Crema'),
('Tarta de Limón con Fresas'),
('Pastel de Almendra con Chocolate'),
('Cheesecake de Frutas'),
('Pie de Chocolate y Avellanas'),
('Pastel de Vainilla con Fresas'),
('Helado de Limón'),
('Tarta de Chocolate con Avellanas'),
('Cheesecake de Fresa y Chocolate'),
('Pastel de Cereza'),
('Tarta de Almendra y Chocolate'),
('Pie de Chocolate y Frambuesa'),
('Tarta de Vainilla con Frutos Rojos'),
('Pastel de Frutas con Crema'),
('Cheesecake de Limón y Arándanos'),
('Helado de Frutas del Bosque'),