# Usa una imagen base oficial de Node.js
FROM node:20.15.1

# Establece el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Copia el script wait-for-it.sh y dale permisos de ejecución
COPY wait-for-it.sh /usr/src/app/wait-for-it.sh
RUN chmod +x /usr/src/app/wait-for-it.sh

# Expone el puerto en el que la aplicación escucha
EXPOSE 3000

# Define el comando a ejecutar al iniciar el contenedor"./wait-for-it.sh", "db", "--", 
CMD ["node", "server.js"]