services:
  web:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mariadb:11.2.4
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: desserts_db
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "8085:80"
    volumes:
      - ./app/public:/usr/share/nginx/html
    depends_on:
      - web

volumes:
  db_data:
